import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'post',
  title: 'Article',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      description: 'The H1. Lead with the keyword you want to rank for.',
      validation: (rule) => rule.required().max(80).warning('Titles over 80 characters get truncated in search results.'),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: { source: 'title', maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Used as the meta description and the card summary. Aim for 150-160 characters.',
      validation: (rule) =>
        rule.required().min(70).max(200).warning('Between 150 and 160 characters reads best in search results.'),
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published at',
      type: 'datetime',
      group: 'content',
      initialValue: () => new Date().toISOString(),
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'updatedAt',
      title: 'Last updated',
      type: 'datetime',
      group: 'content',
      description: 'Set this when you materially revise the article. Drives article:modified_time.',
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{ type: 'author' }],
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'category' }],
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover image',
      type: 'image',
      options: { hotspot: true },
      group: 'content',
      description: 'Also used as the Open Graph image at 1200x630.',
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alt text',
          validation: (rule) => rule.required(),
        },
      ],
    }),
    defineField({
      name: 'body',
      title: 'Body',
      type: 'blockContent',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      group: 'content',
      initialValue: false,
      description: 'Pins the article to the top of the blog index.',
    }),
    defineField({
      name: 'targetKeyword',
      title: 'Target keyword',
      type: 'string',
      group: 'seo',
      description: 'The single query this article is written to win. One per article.',
    }),
    defineField({
      name: 'keywords',
      title: 'Supporting keywords',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'seo',
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta title override',
      type: 'string',
      group: 'seo',
      description: 'Only set this when the <title> should differ from the H1.',
      validation: (rule) => rule.max(60).warning('Google truncates around 60 characters.'),
    }),
    defineField({
      name: 'noIndex',
      title: 'Hide from search engines',
      type: 'boolean',
      group: 'seo',
      initialValue: false,
    }),
  ],
  orderings: [
    {
      title: 'Newest first',
      name: 'publishedAtDesc',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
  ],
  preview: {
    select: { title: 'title', subtitle: 'targetKeyword', media: 'coverImage' },
  },
})
